spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-test
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api


